# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Minmunui Blog
email: ehdwls1638@gmail.com
baseurl: "https://minmunui.github.io/blog"
locale: 'ko-KR'
description: >- # this means to ignore newlines until "baseurl:"
  컴퓨터공학, 인공지능, 그 외의 잡담들을 쓰고 있는 블로그입니다.
twitter_username: minmunui
github_username: minmunui
minimal_mistakes_skin: "dark"
search: true
logo: /assets/images/logo.png
repository: "minmunui/blog"

breadcrumbs: true
show_date: true
date_format: "%Y-%m-%d"

enable_copy_code_button: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

teaser: /assets/images/thumbnails/teaser.jpg
og_image: /assets/images/thumbnails/teaser.jpg

collections:
    # _tutorials
    tutorials:
        output: true
        permalink: /:collection/:path/
    # _pages
    pages:
      output: true
      permalink: /:title/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Dongjin Park"
  avatar: "/assets/images/bio-photo.jpeg"
  bio: "컴퓨터공학을 전공하고 있습니다."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://minmunui.github.io/blog/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/minmunui"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jinee_dong"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/minmunui"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jinee_dong"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      teaser: /assets/images/thumbnails/teaser.jpg
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _tutorials
  - scope:
      path: "_tutorials"
      type: tutorials
    values:
        layout: single
        author_profile: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
